language: node_js
node_js:
- '6'
notifications:
  email:
    recipients:
    - azat.io16@yandex.ru
    on_success: always
    on_failure: always
script:
- npm run test
deploy:
  api_key:
    secure: Mn4ChvaViSM9eguKMQTi6u+MjHTesWPQTVr7ipwder+vbS8Am1BfUwv/gT+QaOmB7dIe44R7EG4EwHXrBs5mNTwgJcgy1BtoA6LwxPre0N8xFAeBoISXYHivpN82o7fxBEcZbA0RzE43w15kRPjvMgMNKsY9q8H/Xb0fTxKP2aJtjuB2vl/uW12pvXjqCb9pmAij7wgX3T3rg2yyLMrLUnZcjjaHyJgMdcKYx5sYfX/w0rmwZ5Knjl65LXaeEcxfcJG+6+ysffkTWDlcoOEw4BESaSlG3jVNDYgo155w2qqGXlyYgPg31aWbVKOQSqSJVg4VgbQFZSnFbwtKJIzcv1pS2qtkCWUdCXGPSOgfIV7EsNp+JxhPapRIWZlvl5YxOkcGLIh99G0o/Pdx4rvwHEiyWP1NI4fvlxERWl6bTWiZxaovzMsJVoki1inJfonkYhEQ77ujGKsulmjLYRBfUhq57zcCTmgXCIkvdkppfLA1nERlXH7vVOlmbz/SgO3cc6sMFBl/fQVMm9lSZ4f83MrWPz1mUbyqfC8sEjCnyy4JfevCCjTR2FDF8y5KLjMWGadNAwZLWvR1uctF49Kt+KOy8y2Ol1QQVvbBr3hEhafHafKlklsU9HxRUnNbJCFk0skLF6pJw5FhBxfgEJ4i04agpVgkNFWWKPZlZAL5VZo=
